### ISSUE TITLE
sources ? 

### ISSUE THREAD

**Issue by mc007** [LeaVerou/cubic-bezier#6]
Hi, 
there are some 'min' files, do you have the source code for this by chance ? I'd like to pimp this a little for more 'control-points' etc...
Thank you!
g

**Comment by LeaVerou** [comment]
Are you referring to chainvas? It’s the only one whose source isn’t in the repo. You can find it here: https://github.com/LeaVerou/chainvas

**Comment by mc007** [comment]
ups, yes, that was the one. thank you very much !
